// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFPaYxSb22M7Ire7nDSjUIUPq2Ye0FETU',
    appId: '1:902045358120:web:04e5b32c38856f85893d1d',
    messagingSenderId: '902045358120',
    projectId: 'kuyupjelantah-mobile',
    authDomain: 'kuyupjelantah-mobile.firebaseapp.com',
    storageBucket: 'kuyupjelantah-mobile.firebasestorage.app',
    measurementId: 'G-QM4YP0HZKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiZlA51xjHsmOZfq5asJk8teObpT7ef-Y',
    appId: '1:902045358120:android:b02fd098892f83e6893d1d',
    messagingSenderId: '902045358120',
    projectId: 'kuyupjelantah-mobile',
    storageBucket: 'kuyupjelantah-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA446cUvBExWjWpIaNUx94-jrYF1mPwz0k',
    appId: '1:902045358120:ios:1826243a1b0c5835893d1d',
    messagingSenderId: '902045358120',
    projectId: 'kuyupjelantah-mobile',
    storageBucket: 'kuyupjelantah-mobile.firebasestorage.app',
    iosBundleId: 'com.example.kuyupjelantah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA446cUvBExWjWpIaNUx94-jrYF1mPwz0k',
    appId: '1:902045358120:ios:1826243a1b0c5835893d1d',
    messagingSenderId: '902045358120',
    projectId: 'kuyupjelantah-mobile',
    storageBucket: 'kuyupjelantah-mobile.firebasestorage.app',
    iosBundleId: 'com.example.kuyupjelantah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFPaYxSb22M7Ire7nDSjUIUPq2Ye0FETU',
    appId: '1:902045358120:web:e6e69f7b2ac81658893d1d',
    messagingSenderId: '902045358120',
    projectId: 'kuyupjelantah-mobile',
    authDomain: 'kuyupjelantah-mobile.firebaseapp.com',
    storageBucket: 'kuyupjelantah-mobile.firebasestorage.app',
    measurementId: 'G-3D7SLLJ85G',
  );
}
